language: java

script: xvfb-run ./gradlew check

# Shamelessly copied from https://www.hoverbear.org/2015/03/07/rust-travis-github-pages/#givingtravispermissions and modified for Java
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  gradle javadocAll &&
  pip install ghp-import --user && export PATH=$HOME/.local/bin:$PATH &&
  ghp-import -n build/javadoc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
